version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    open-pull-requests-limit: 10
    groups:
      gradle-dependencies:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
      gradle-patch-updates:
        update-types:
          - "patch"
    schedule:
      interval: cron
      cronjob: "0 0 1,15 * *"
    target-branch: "develop"
    labels:
      - "dependency"
      - "gradle"
    commit-message:
      prefix: "[DT-400-gradle]"
