def garProjectId = System.getenv("GOOGLE_CLOUD_PROJECT")
def garLocation = System.getenv("GAR_LOCATION")
def garRepoId = System.getenv("GAR_REPOSITORY_ID")

apply plugin: 'java'

publishing {
    publications {
        stairwayLibrary(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url = uri("artifactregistry://${garLocation}-maven.pkg.dev/${garProjectId}/${garRepoId}")
        }
    }
}