name: master version bump
on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ master ]
    paths-ignore: [ '**.md' ]
  workflow_dispatch:
    inputs:
      bump:
        description: 'Part of the version to bump: major, minor, patch'
        required: false
        default: 'patch'
      branch:
        description: 'Branch to run the workflow on'
        required: false
        default: 'master'

permissions:
  contents: read
  id-token: write

jobs:
  master-tag-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set part of semantic version to bump
        id: semver
        run: |
          SEMVER_PART=""
          CHECKOUT_BRANCH="$GITHUB_REF"
          if ${{github.event_name == 'push' }}; then
            SEMVER_PART="patch"
          elif ${{github.event_name == 'workflow_dispatch' }}; then
            SEMVER_PART=${{ github.event.inputs.bump }}
            CHECKOUT_BRANCH=${{ github.event.inputs.branch }}
          fi
          echo semver-part=$SEMVER_PART >> $GITHUB_OUTPUT
          echo checkout-branch=$CHECKOUT_BRANCH >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.semver.outputs.checkout-branch }}
      - name: "Bump the tag to a new version"
        uses: databiosphere/github-actions/actions/bumper@bumper-0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: master,develop
          VERSION_FILE_PATH: settings.gradle
          VERSION_LINE_MATCH: "^gradle.ext.version\\s*=\\s*\".*\""
      - name: "Set up JDK"
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v3
        with:
          token_format: access_token
          workload_identity_provider: 'projects/1038484894585/locations/global/workloadIdentityPools/github-wi-pool/providers/github-wi-provider'
          service_account: 'dsp-artifact-registry-push@dsp-artifact-registry.iam.gserviceaccount.com'
      - name: Publish client to GAR
        run: ./gradlew publish
        env:
          GOOGLE_CLOUD_PROJECT: dsp-artifact-registry
          GAR_LOCATION: us-central1
          GAR_REPOSITORY_ID: libs-snapshot-standard
